version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongoui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH=false
    ports:
      - 8080:8081
    networks:
      - mongo-database

networks:
  mongo-database:
    driver: bridge
volumes:
  mongodata:
    driver: local
